package bean.daoBean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import bean.daoBean.likefilmbean;
import bean.daoBean.localfilmBean;

import bean.daoBean.likefilmbeanDao;
import bean.daoBean.localfilmBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig likefilmbeanDaoConfig;
    private final DaoConfig localfilmBeanDaoConfig;

    private final likefilmbeanDao likefilmbeanDao;
    private final localfilmBeanDao localfilmBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        likefilmbeanDaoConfig = daoConfigMap.get(likefilmbeanDao.class).clone();
        likefilmbeanDaoConfig.initIdentityScope(type);

        localfilmBeanDaoConfig = daoConfigMap.get(localfilmBeanDao.class).clone();
        localfilmBeanDaoConfig.initIdentityScope(type);

        likefilmbeanDao = new likefilmbeanDao(likefilmbeanDaoConfig, this);
        localfilmBeanDao = new localfilmBeanDao(localfilmBeanDaoConfig, this);

        registerDao(likefilmbean.class, likefilmbeanDao);
        registerDao(localfilmBean.class, localfilmBeanDao);
    }
    
    public void clear() {
        likefilmbeanDaoConfig.clearIdentityScope();
        localfilmBeanDaoConfig.clearIdentityScope();
    }

    public likefilmbeanDao getLikefilmbeanDao() {
        return likefilmbeanDao;
    }

    public localfilmBeanDao getLocalfilmBeanDao() {
        return localfilmBeanDao;
    }

}
