package bean.daoBean;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LIKEFILMBEAN".
*/
public class likefilmbeanDao extends AbstractDao<likefilmbean, Long> {

    public static final String TABLENAME = "LIKEFILMBEAN";

    /**
     * Properties of entity likefilmbean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property From = new Property(2, String.class, "from", false, "FROM");
        public final static Property Url = new Property(3, String.class, "url", false, "URL");
        public final static Property Introduce = new Property(4, String.class, "introduce", false, "INTRODUCE");
        public final static Property Img = new Property(5, String.class, "img", false, "IMG");
        public final static Property Date = new Property(6, String.class, "date", false, "DATE");
        public final static Property Tag = new Property(7, String.class, "tag", false, "TAG");
        public final static Property Comment = new Property(8, String.class, "comment", false, "COMMENT");
        public final static Property BmobID = new Property(9, String.class, "bmobID", false, "BMOB_ID");
    }


    public likefilmbeanDao(DaoConfig config) {
        super(config);
    }
    
    public likefilmbeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LIKEFILMBEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"FROM\" TEXT," + // 2: from
                "\"URL\" TEXT NOT NULL ," + // 3: url
                "\"INTRODUCE\" TEXT," + // 4: introduce
                "\"IMG\" TEXT," + // 5: img
                "\"DATE\" TEXT," + // 6: date
                "\"TAG\" TEXT," + // 7: tag
                "\"COMMENT\" TEXT," + // 8: comment
                "\"BMOB_ID\" TEXT);"); // 9: bmobID
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LIKEFILMBEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, likefilmbean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String from = entity.getFrom();
        if (from != null) {
            stmt.bindString(3, from);
        }
        stmt.bindString(4, entity.getUrl());
 
        String introduce = entity.getIntroduce();
        if (introduce != null) {
            stmt.bindString(5, introduce);
        }
 
        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(6, img);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(7, date);
        }
 
        String tag = entity.getTag();
        if (tag != null) {
            stmt.bindString(8, tag);
        }
 
        String comment = entity.getComment();
        if (comment != null) {
            stmt.bindString(9, comment);
        }
 
        String bmobID = entity.getBmobID();
        if (bmobID != null) {
            stmt.bindString(10, bmobID);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, likefilmbean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String from = entity.getFrom();
        if (from != null) {
            stmt.bindString(3, from);
        }
        stmt.bindString(4, entity.getUrl());
 
        String introduce = entity.getIntroduce();
        if (introduce != null) {
            stmt.bindString(5, introduce);
        }
 
        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(6, img);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(7, date);
        }
 
        String tag = entity.getTag();
        if (tag != null) {
            stmt.bindString(8, tag);
        }
 
        String comment = entity.getComment();
        if (comment != null) {
            stmt.bindString(9, comment);
        }
 
        String bmobID = entity.getBmobID();
        if (bmobID != null) {
            stmt.bindString(10, bmobID);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public likefilmbean readEntity(Cursor cursor, int offset) {
        likefilmbean entity = new likefilmbean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // from
            cursor.getString(offset + 3), // url
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // introduce
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // img
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // date
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // tag
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // comment
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // bmobID
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, likefilmbean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setFrom(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUrl(cursor.getString(offset + 3));
        entity.setIntroduce(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setImg(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDate(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setTag(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setComment(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setBmobID(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(likefilmbean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(likefilmbean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(likefilmbean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
